"""empty message

Revision ID: 93150d43ef21
Revises: 495e22f55c42
Create Date: 2022-12-05 01:02:40.998949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93150d43ef21'
down_revision = '495e22f55c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_column('past')

    # ### end Alembic commands ###
